{
    parserClass="net.weixy.autotest.selenium.ObjectMapParser"
    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
    psiClassPrefix="ObjectMap"
    psiImplClassSuffix="Impl"
    psiPackage="net.weixy.autotest.selenium.psi"
    psiImplPackage="net.weixy.autotest.selenium.psi.impl"
    elementTypeHolderClass="net.weixy.autotest.selenium.psi.ObjectMaps"
    elementTypeClass="net.weixy.autotest.selenium.psi.ObjectMapElementType"
    tokenTypeClass="net.weixy.autotest.selenium.psi.ObjectMapTokenType"

    tokens=[
        ID="id"
        XPATH="xpath"
        CSS="cssselector"
        TXT="textequal"
        CONTAIN="containtext"
        LABEL="label"

        comment='regexp:^#.*'
        property='regexp:^\w+(\.\w+)*(?=\=)'
        expression='regexp:(?:):(.*)'

    ]
}
map ::= ( object | comment ) *
object ::= property '=' by expression
by ::= ID | XPATH | CSS | TXT | CONTAIN | LABEL