{
    parserClass="net.weixy.autotest.selenium.ObjectMapParser"
    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
    psiClassPrefix="ObjectMap"
    psiImplClassSuffix="Impl"
    psiPackage="net.weixy.autotest.selenium.psi"
    psiImplPackage="net.weixy.autotest.selenium.psi.impl"
    elementTypeHolderClass="net.weixy.autotest.selenium.psi.ObjectMapTypes"
    elementTypeClass="net.weixy.autotest.selenium.ObjectMapElementType"
    tokenTypeClass="net.weixy.autotest.selenium.ObjectMapTokenType"

    tokens=[
        ID="id"
        XPATH="xpath"
        CSS="cssselector"
        TXT="textequal"
        CONTAIN="containtxt"
        LABEL="label"
        NEW_LINE="\n\r|\r|\n"

        separator='='
        comment='regexp:^#.*'
        property='regexp:^\w+(\.\w+)*(?=\=)'
        expression='regexp:(?:):(.*)'

    ]
}
map ::= ( object | comment ) *
object ::= property separator by expression
by ::= ID | XPATH | CSS | TXT | CONTAIN | LABEL